name: todos
description: A new Flutter project.
publish_to: "none"

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  freezed_annotation: ^3.0.0
  hooks_riverpod:
  json_annotation: ^4.9.0
  riverpod:
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0
  json_serializable: ^6.9.5
  riverpod_lint:

flutter:
  uses-material-design: true
