name: todos
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1
  hooks_riverpod: ^2.4.9
  riverpod: ^2.4.9
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0
  json_serializable: ^6.7.1
  riverpod_lint: ^2.3.7
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
